[package]
name = "archive-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
jsonwebtoken = "8.3.0"
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
